### PR TITLE
Switch CLI dependency from docopt to Click and make it optional

### PR DESCRIPTION
**Pull request by BLKSerene**
Following #16, instead of replacing the abandoned `docopt` with a forked version, this PR switch from `docopt` to `Click` which is in active development. Command line usages are unchanged, except some minor differences in the format of the generated help text.

I'll leave the decision to the maintainers of this fork as for whether it is worth it for future development.

### CODE REVIEW

**Comment by insolor** [comment]
pymorphy3 formally is still supports python2, so I think it makes sense first to drop support of older versions of Python, then upgrade to only-python3 dependencies.

Also, I'd suggest to make CLI dependencies optional.

**Comment by BLKSerene** [comment]
@insolor Optional CLI dependencies is more preferable to me, do you mean:
```
extras_require={
    'CLI': ['click'],
}
```
What about the opinions of other maintainers?

And it is better to handle the drop of Python 2 (and maybe older Python 3 versions) support (the PY2 checks in `cli.py` along with Python 2 codes in other files) in another separate PR.

**Comment by insolor** [comment]
@BLKSerene, yes, I mean `extras_require`. And also try/except around `import click` in cli.py, so that cli would show meaningfull message instead of ImportError.

**Comment by BLKSerene** [comment]
@insolor Done.

**Comment by BLKSerene** [comment]
Any updates?

**Review by d9nchik — APPROVED** [review]

**Pull request merged**
